# Generated by Django 5.2.3 on 2025-08-21 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='dis',
        ),
        migrations.AddField(
            model_name='topping',
            name='pizza_name',
            field=models.CharField(default='pineapple', max_length=100),
        ),
    ]
