# Generated by Django 5.2.3 on 2025-08-21 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
